#page title
page_title                                : LunarCrown Games                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : #1336687974                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/us/app/dots-of-war/id1480146910                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.LunarCrown.DotsOfWar                                       # Enter Google Play Store URL.
presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Dots of War                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : LunarCrown is developing Dots of War, a fast paced strategy games for mobile.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : LunarCrown                               
your_link                                 : https://lunarcrown.com                     
your_city                                 : Hermosillo, Mexico                                
email_address                             : hello@lunarcrown.com
facebook_username                         : lunarcrown                                          
instagram_username                        : lunarcrown_
twitter_username                          : LunarCrownGames
github_username                           : ucamo
youtube_username                          : LunarCrown Games



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : The Game
    description                           : Join 4 dots with lines to capture the territory, the player who capture the most wins!
    fontawesome_icon_name                 : chess-board
    
  - title                                 : The clans
    description                           : Select from 3 different characters each with special skills during combat.
    fontawesome_icon_name                 : mobile

  - title                                 : Features
    description                           : A fast paced combat between two players, collect bonus items to help you in the match.
    fontawesome_icon_name                 : puzzle-piece
    
  - title                                 : Gameskeys
    description                           : The best game to demonstrate your skill with puzzles
    fontawesome_icon_name                 : pencil-alt
    
   - title                                 : El Sol de Hermosillo [ES]
    description                           :  Dots of War, el videojuego dise√±ado en estudio independiente de Hermosillo
    fontawesome_icon_name                 : pencil-alt



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown

url: "http://lunarcrown.com"
plugins:
  - jekyll-seo-tag
   - jekyll-sitemap
